- hosts: localhost
  connection: local
  become: yes

  vars:
    arduino_version: "1.8.11"
    arduino_url: "https://downloads.arduino.cc/arduino-{{ arduino_version }}-linux64.tar.xz"
    arduino_tmp: "/tmp/arduino"

  tasks:

    - name: ARDUINO - Install aptitude
      apt:
        name: aptitude

    - name: ARDUINO - install prereqs
      apt:
        name: ['tar',
              'xz-utils']
        state: present

    - name: ARDUINO - Creates temporary directory
      file:
        path: "{{ arduino_tmp }}"
        state: directory

    - name: ARDUINO - Download archive
      get_url:
        url: "{{ arduino_url }}"
        dest: "{{ arduino_tmp }}/arduino.tar.xz"
        force: yes

    - name: ARDUINO - Extract archive
      unarchive:
        src: "{{ arduino_tmp }}/arduino.tar.xz"
        dest: /opt
        remote_src: no

    - name: ARDUINO - Install IDE
      shell: "/opt/arduino-{{ arduino_version }}/install.sh"

    - name: ARDUINO - Remove temporary directory
      file:
        path: "{{ arduino_tmp }}"
        state: absent
