- hosts: localhost
  connection: local
  become: yes

  vars :
    azure_tmp: /tmp/azure
    azcopy_name: azcopy_linux_amd64_10.2.1
    azcopy_url: https://azcopyvnext.azureedge.net/release20190703/{{ azcopy_name }}.tar.gz

  tasks:

    - name: install cifs-utils
      apt:
        name: cifs-utils
        state: present

    - name: install powershell Microsoft repository
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        update_cache: true

    - name: install powershell
      apt:
        name: powershell
        state: present
        update_cache: true

    - name: install powershell azure module
      command: "pwsh -noni -c 'Install-Module -Force -Name Az -AllowClobber'"

    - name: install powershell MsOnline module
      command: "pwsh -noni -c 'Install-Module -Force -Name MsOnline -AllowClobber'"

    - name: import powershell MsOnline module
      command: "pwsh -noni -c 'Import-Module MSonline'"

    - name: install microsoft azure-cli key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present

    - name: install microsoft azure-cli repository
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main'
        state: present

    - name: install azure-cli
      apt:
        name: azure-cli
        state: present

    - name: Creates azure temporary directory
      become: yes
      file:
        path: "{{ azure_tmp }}"
        state: directory

    - name: download azcopy
      get_url:
        url: "{{ azcopy_url }}"
        dest: "{{ azure_tmp }}/azcopy.tar.gz"
        force: yes

    - name: extract azcopy
      unarchive:
        src: '{{ azure_tmp }}/azcopy.tar.gz'
        dest: /opt
        copy: no

    - name: Create symbolic link
      become: yes
      file:
        src: "/opt/{{ azcopy_name }}/azcopy"
        dest: "/usr/bin/azcopy"
        state: link

    - name: Remove azure temporary directory
      become: yes
      file:
        path: "{{ azure_tmp }}"
        state: absent
