- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: install powershell Microsoft repository
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        update_cache: true

    - name: install powershell
      apt:
        name: powershell
        state: present

    - name: install powershell azure module
      command: "pwsh -noni -c 'Install-Module -Force -Name Az -AllowClobber'"

    - name: install microsoft azure-cli key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present

    - name: install microsoft azure-cli repository
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main'
        state: present

    - name: install azure-cli
      apt:
        name: azure-cli
        state: present


