- hosts: localhost
  connection: local

  tasks:

    - name: install aptitude
      become: yes
      apt:
        name:
          - aptitude
        state: present

    - name: install codecs
      become: yes
      apt:
        name:
          - ubuntu-restricted-extras
        state: present

    - name: install git
      become: yes
      apt:
        name:
          - git
        state: present

    - name: install rar
      become: yes
      apt:
        name:
          - rar
          - unrar
        state: present

    - name: install sushi
      become: yes
      apt:
        name:
          - gnome-sushi
        state: present

    - name: install vlc
      become: yes
      apt:
        name:
          - vlc
        state: present