- hosts: localhost
  connection: local

  tasks:

    - name: BASIC - install aptitude
      become: yes
      apt:
        name:
          - aptitude
        state: present

    - name: BASIC - install codecs
      become: yes
      apt:
        name:
          - ubuntu-restricted-extras
        state: present

    - name: BASIC - install network tools
      become: yes
      apt:
        name:
          - curl
          - wget
          - net-tools
        state: present

    - name: BASIC - install git
      become: yes
      apt:
        name:
          - git
        state: present

    - name: BASIC - install rar
      become: yes
      apt:
        name:
          - rar
          - unrar
        state: present

    - name: BASIC - install sushi
      become: yes
      apt:
        name:
          - gnome-sushi
        state: present

    - name: BASIC - install vlc
      become: yes
      apt:
        name:
          - vlc
        state: present

    - name: BASIC - install samba
      become: yes
      apt:
        name:
          - samba
        state: present        

    - name: BASIC - install openvpn
      become: yes
      apt:
        name:
          - openvpn
          - openresolv
        state: present

    - name: BASIC - install jq
      become: yes
      apt:
        name:
          - jq
        state: present

