- hosts: localhost
  connection: local

  tasks:

    - name: BASIC - install bascis
      become: yes
      apt:
        name:
          # aptitude
          - aptitude
          # codecs
          - ubuntu-restricted-extras
          # network tools
          - curl
          - wget
          - net-tools
          - httpie
          # git (source control)
          - git
          # vim (editor)
          - vim
          # archive application
          - rar
          - unrar
          - zip
          - unzip
          - p7zip-full
          - p7zip-rar
          # sushi
          - gnome-sushi
          #  vlc (media player)
          - vlc
          # samba (shared ressources)
          - samba
          # jq (JSON Query)
          - jq
          # dconf-editor
          - dconf-editor
          # ncdu (disk usage)
          - ncdu
          # htop (ressources)
          - htop
          # direnv (autoset env)
          - direnv
          # mtr (trace route)
          - mtr
        state: present

    - name: BASIC - Set vim editor for git
      git_config:
        name: core.editor
        scope: global
        value: vim

    - name: BASIC - Store credential for git
      git_config:
        name: credential.helper
        scope: global
        value: store

    - name: BASIC - Add color config for git
      git_config:
        name: "{{ item }}"
        scope: global
        value: auto
      with_items:
        - color.branch
        - color.diff
        - color.interactive
        - color.status
        - color.grep
