- hosts: localhost
  connection: local

  tasks:

    - name: BASIC - install bascis
      become: yes
      apt:
        name:
          # aptitude
          - aptitude
          # codecs
          - ubuntu-restricted-extras
          # network tools
          - curl
          - wget
          - net-tools
          # git
          - git
          # vim
          - vim
          # archive application
          - rar
          - unrar
          - zip
          - unzip
          - p7zip-full
          - p7zip-rar
          # sushi
          - gnome-sushi
          #  vlc
          - vlc
          # samba
          - samba
          # openvpn
          - openvpn
          - openresolv
          # jq
          - jq
          # httpie
          - httpie
          # dconf-editor
          - dconf-editor
          # ncdu
          - ncdu
          # htop
          - htop
          # direnv
          - direnv
        state: present

    - name: Set vim editor for git
      git_config:
        name: core.editor
        scope: global
        value: vim

    - name: Add color config for git
      git_config:
        name: alias.ci
        scope: global
        value: auto
      with_items:
        - color.branch
        - color.diff
        - color.interactive
        - color.status
        - color.grep
