- hosts: localhost
  connection: local

  tasks:

    - name: BASIC - install aptitude
      become: yes
      apt:
        name:
          - aptitude
        state: present

    - name: BASIC - install codecs
      become: yes
      apt:
        name:
          - ubuntu-restricted-extras
        state: present

    - name: BASIC - install git
      become: yes
      apt:
        name:
          - git
        state: present

    - name: BASIC - install rar
      become: yes
      apt:
        name:
          - rar
          - unrar
        state: present

    - name: BASIC - install sushi
      become: yes
      apt:
        name:
          - gnome-sushi
        state: present

    - name: BASIC - install vlc
      become: yes
      apt:
        name:
          - vlc
        state: present