- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: BORGBACKUP - Install package
      apt:
        name: 
         - borgbackup
         - python3-pip
        state: present    

    - name: BORGBACKUP - install vorta
      pip:
        executable: pip3
        name:
          - vorta
          - PyQt5
