- hosts: localhost
  connection: local
  become: yes

  vars:
    #citrix_url: "https://downloads.citrix.com/16537/icaclient_19.8.0.20_amd64.deb?__gda__=1568648662_ea2d403d6bbfd4ffb39ca4474973263d"
    citrix_url: "https://downloads.citrix.com/16537/icaclientWeb_19.8.0.20_amd64.deb?__gda__=1568650703_ba06bb4266074f043c52dcdbfe1ef5c5"
    citrix_tmp: "/tmp/citrix"

  tasks:

    - name: CITRIX - Creates temporary directory
      file:
        path: "{{ citrix_tmp }}"
        state: directory

    - name: CITRIX - Download package
      get_url:
        url: "{{ citrix_url }}"
        dest: "{{ citrix_tmp }}/citrix.deb"
        force: yes

    - name: CITRIX - Install package
      apt:
        deb: "{{ citrix_tmp }}/citrix.deb"

    - name: CITRIX - Remove temporary directory
      file:
        path: "{{ citrix_tmp }}"
        state: absent
