- hosts: localhost
  connection: local

  tasks:

    - name: Creates application directory
      become: yes
      file:
        path: "/opt/cura"
        state: directory

    - name: Download application
      become: yes
      get_url:
        url: 'https://software.ultimaker.com/cura/Ultimaker_Cura-4.2.1.AppImage'
        dest: '/opt/cura/cura.AppImage'
        mode: 775
        force: yes

    - name: Copy icon image
      copy:
        src: files/cura.png
        dest: /opt/cura/icon.png

    - name: Create symbolic link
      become: yes
      file:
        src: "/opt/cura/cura.AppImage"
        dest: "/usr/bin/cura"
        state: link

    - name: create shortcut
      template:
        src: templates/cura.j2
        dest: ~/.local/share/applications/cura.desktop
