- hosts: localhost
  connection: local

  tasks:

    - name: CURA - creates application directory
      become: yes
      file:
        path: "/opt/cura"
        state: directory

    - name: CURA - Download application
      become: yes
      get_url:
        url: 'https://software.ultimaker.com/cura/Ultimaker_Cura-4.8.0.AppImage'
        dest: '/opt/cura/cura.AppImage'
        mode: 775
        force: yes

    - name: CURA - Copy icon image
      become: yes
      copy:
        src: files/cura.png
        dest: /opt/cura/icon.png

    - name: CURA - Create symbolic link
      become: yes
      file:
        src: "/opt/cura/cura.AppImage"
        dest: "/usr/bin/cura"
        state: link

    - name: CURA - create shortcut
      template:
        src: templates/cura.j2
        dest: ~/.local/share/applications/cura.desktop
