- hosts: localhost
  connection: local
  become: yes

  vars:
    dive_url: https://github.com/wagoodman/dive/releases/download/v0.9.1/dive_0.9.1_linux_amd64.deb
    dive_tmp: /tmp/dive

  tasks:

    - name: DIVE - Creates temporary directory
      file:
        path: "{{ dive_tmp }}"
        state: directory

    - name: DIVE - Download dive
      get_url:
        url: "{{ dive_url }}"
        dest: "{{ dive_tmp }}/dive.deb"
        force: yes

    - name: DIVE - Install dive package
      apt:
        deb: "{{ dive_tmp }}/dive.deb"

    - name: DIVE - Remove temporary directory
      file:
        path: "{{ dive_tmp }}"
        state: absent
