- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: Install docker
      include_role:
        name: ansible-role-docker
      vars:
        docker_edition: 'ce'
        docker_package: "docker-{{ docker_edition }}"
        docker_package_state: present
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted
        docker_install_compose: true
        docker_compose_version: "1.23.2"
        docker_compose_path: /usr/bin/docker-compose
        docker_users:
          - "{{ username_on_the_host.stdout }}"

        
