- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: DOCKER - get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: DOCKER - Install docker
      include_role:
        name: docker
      vars:
        docker_users: ["{{ username_on_the_host.stdout }}"]

    - name: DOCKER - remove remap configuration
      file:
        path: "/etc/docker/daemon.json"
        state: absent

    - name: DOCKER - restart docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker


