- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: DROPBOX - add dropbox apt key
      apt_key:
        id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
        keyserver: pgp.mit.edu
        state: present

    - name: DROPBOX - add dropbox repo
      apt_repository:
        repo: deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu bionic main
        state: present
        update_cache: yes

    - name: DROPBOX - install dropbox
      apt:
        name: dropbox
        state: present
