- hosts: localhost
  connection: local
  become: no

  vars:
    - etcher_version: 1.5.102
    - etcher_url: "https://github.com/balena-io/etcher/releases/download/v{{ etcher_version }}/balena-etcher-electron-{{ etcher_version }}-linux-x64.zip"
    - etcher_dir: "/opt/etcher"

  tasks:

    - name: ETCHER - creates application directory
      become: yes
      file:
        path: "{{ etcher_dir }}"
        state: directory

    - name: ETCHER - Download and extract application
      become: yes
      unarchive:
        src: "{{ etcher_url }}"
        dest: "{{ etcher_dir }}"
        remote_src: yes

    - name: ETCHER - Copy icon image
      become: yes
      copy:
        src: files/etcher.png
        dest: "{{ etcher_dir }}/icon.png"

    - name: ETCHER - Create symbolic link
      become: yes
      file:
        src: "/opt/etcher/balenaEtcher-{{ etcher_version }}-x64.AppImage"
        dest: "/usr/bin/balenaEtcher"
        state: link

    - name: ETCHER - create shortcut
      template:
        src: templates/etcher.j2
        dest: ~/.local/share/applications/etcher.desktop

