- hosts: localhost
  connection: local
  become: no

  vars:
    - etcher_project: balena-io/etcher
    - etcher_dir: "/opt/etcher"

  tasks:

    - name: ETCHER - creates application directory
      become: yes
      file:
        path: "{{ etcher_dir }}"
        state: directory

    - name: ETCHER - Get latest release
      uri:
        url: "https://api.github.com/repos/{{ etcher_project }}/releases/latest"
        return_content: yes
      register: etcher_release

    - name: ETCHER - View latest release
      debug:
        msg: "{{ etcher_release.json.tag_name }}"

    - name: ETCHER - Download and extract application
      become: yes
      unarchive:
        src: "https://github.com/{{ etcher_project }}/releases/download/{{ etcher_release.json.tag_name }}/balena-etcher-electron-{{ etcher_release.json.tag_name | regex_replace('^v') }}-linux-x64.zip"
        dest: "{{ etcher_dir }}"
        remote_src: yes

    - name: ETCHER - Copy icon image
      become: yes
      copy:
        src: files/etcher.png
        dest: "{{ etcher_dir }}/icon.png"

    - name: ETCHER - Create symbolic link
      become: yes
      file:
        src: "/opt/etcher/balenaEtcher-{{ etcher_release.json.tag_name | regex_replace('^v')  }}-x64.AppImage"
        dest: "/usr/bin/balenaEtcher"
        state: link

    - name: ETCHER - create shortcut
      template:
        src: templates/etcher.j2
        dest: ~/.local/share/applications/etcher.desktop

