- hosts: localhost
  connection: local

  vars:
    gimp_url: https://raw.githubusercontent.com/doctormo/GimpPs/master/tools/install.sh
    gimp_tmp: /tmp/gimp

  tasks:

    - name: GIMP - install gimp (apt)
      become: yes
      apt:
        name: gimp
        state: present

    - name: GIMP - Creates gimp theme temporary directory
      file:
        path: "{{ gimp_tmp }}"
        state: directory

    - name: GIMP - Download install script gimp theme
      get_url:
        url: "{{ gimp_url }}"
        dest: "{{ gimp_tmp }}/install.sh"
        force: yes
        mode: "775"

    - name: GIMP - Laucnh install script gimp Theme
      shell: "{{ gimp_tmp }}/install.sh"

    - name: GIMP - Remove gimp temporary directory
      file:
        path: "{{ gimp_tmp }}"
        state: absent