- hosts: localhost
  connection: local

  tasks:

    - name: GO - add repository
      become: yes
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: present

    - name: GO - install package
      become: yes
      apt:
        name:
          - golang-go
        state: present
        update_cache: yes
