- hosts: localhost
  connection: local
  become: yes

  vars:
    helm_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-amd64.tar.gz
    helm_tmp: /tmp/helm

  tasks:

    - name: HELM - Creates temporary directory
      file:
        path: "{{ helm_tmp }}"
        state: directory

    - name: HELM - Download helm
      get_url:
        url: "{{ helm_url }}"
        dest: "{{ helm_tmp }}/helm.tar.gz"
        force: yes

    - name: HELM - Extract archive
      unarchive:
        src: "{{ helm_tmp }}/helm.tar.gz"
        dest: "{{ helm_tmp }}"

    - name: HELM - Move helm to /usr/local/bin/
      command: mv {{ helm_tmp }}/linux-amd64/helm /usr/local/bin/helm

    - name: HELM - Move tiller to /usr/local/bin/
      command: mv {{ helm_tmp }}/linux-amd64/tiller /usr/local/bin/tiller

    - name: HELM - install bash-completion
      apt:
        name: bash-completion
        state: present

    - name: HELM - activate auto-completion for helm
      shell: helm completion bash >/etc/bash_completion.d/helm

    - name: HELM - Remove temporary directory
      file:
        path: "{{ helm_tmp }}"
        state: absent