- hosts: localhost
  connection: local
  become: yes

  vars:
    hyper_url: https://releases.hyper.is/download/deb
    hyper_tmp: /tmp/hyper

  tasks:

    - name: Creates hyper temporary directory
      file:
        path: "{{ hyper_tmp }}"
        state: directory
        
    - name: Download hyper
      get_url:
        url: "{{ hyper_url }}"
        dest: "{{ hyper_tmp }}/hyper.deb"

    - name: Install my_package
      apt:
        deb: "{{ hyper_tmp }}/hyper.deb"

    - name: default configuration
      become: no
      template:
        src: templates/hyper.j2
        dest: ~/.hyper.js

    # - name: install plugins
    #   become: no
    #   command: "hyper install {{ item }}"
    #   with_items:
    #     - "hyperterm-cursor"
    #     - "hyper-blink"
    #     - "hyper-tab-icons"
    #     - "hypercwd"
    #     - "hyper-dracula"
    #     - "hyperline"

    - name: Remove hyper temporary directory
      file:
        path: "{{ hyper_tmp }}"
        state: absent