- hosts: localhost
  connection: local

  tasks:

    - name: install kazam 
      become: yes
      apt:
        name:
          - pavucontrol
          - kazam
          - gnome-alsamixer
        state: present

