- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: KUBECTL - add key
      apt_key:
        url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
        state: present

    - name: KUBECTL - add kubernetes repo
      apt_repository:
        repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes
        state: present

    - name: KUBECTL - install kubectl
      apt:
        name: kubectl
        state: present

    - name: KUBECTL - install bash-completion (apt)
      apt:
        name: bash-completion
        state: present

    - name: KUBECTL - activate auto-completion for kubectl
      shell: kubectl completion bash >/etc/bash_completion.d/kubectl
