- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: add libreOffice repository
      apt_repository:
        repo: ppa:libreoffice/ppa

    - name: Install libreoffice
      apt:
        name: [ "libreoffice", "libreoffice-help-fr", "libreoffice-l10n-fr" ]
