- hosts: localhost
  connection: local

  tasks:

    - name: MINIKUBE - Download and install archive
      become: yes
      get_url:
        url: 'https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64'
        dest: '/usr/local/bin/minikube'
        force: yes
        mode: 0775
