- hosts: localhost
  connection: local

  tasks:

    - name: OPENSTACK - install client app with pip
      become: yes
      pip:
        name:
          - python-openstackclient
          - python-novaclient

