- hosts: localhost
  connection: local

  tasks:

    - name: PS1 - add configuration
      blockinfile:
        dest: ~/.bashrc
        block: "{{ lookup('template', 'templates/ps1.j2') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"