- hosts: localhost
  connection: local
  become: yes

  vars:
    robo3t_version: "1.4.0"
    robo3t_app: "robo3t-{{ robo3t_version }}-linux-x86_64-12e54cc"
    robo3t_url: "https://download.studio3t.com/robomongo/linux/robo3t-{{ robo3t_version }}-linux-x86_64-12e54cc.tar.gz?submissionGuid=6e58e496-8c82-49b0-8ca1-35e82fb68a10"
    robo3t_tmp: "/tmp/robo3t"

  tasks:

    - name: ROBO3T - Creates temporary directory
      file:
        path: "{{ robo3t_tmp }}"
        state: directory

    - name: ROBO3T - Download archive
      get_url:
        url: "{{ robo3t_url }}"
        dest: "{{ robo3t_tmp }}/robo3t.tar.gz"
        force: yes

    - name: ROBO3T - Extract archive
      unarchive:
        src: "{{ robo3t_tmp }}/robo3t.tar.gz"
        dest: /opt
        remote_src: no

    - name: ROBO3T - Copy icon image
      copy:
        src: files/robo3t.png
        dest: /opt/{{ robo3t_app }}/icon.png

    - name: ROBO3T - create shortcut
      become: no
      template:
        src: templates/robo3t.j2
        dest: ~/.local/share/applications/robo3t.desktop

    - name: ROBO3T - Remove temporary directory
      file:
        path: "{{ robo3t_tmp }}"
        state: absent
