- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: RUNDECK - Execute repository script
      shell: |
        curl -s https://packagecloud.io/install/repositories/pagerduty/rundeck/script.deb.sh | os=any dist=any bash

    - name: RUNDECK - install rundeck-cli
      apt:
        name: rundeck-cli
        state: present
