- hosts: localhost
  connection: local
  become: yes

  vars:
    github_project: Automattic/simplenote-electron
    simplenote_tmp: "/tmp/simplenote"

  tasks:

    - name: SIMPLENOTE - Get latest release
      uri:
        url: "https://api.github.com/repos/{{ github_project }}/releases/latest"
        return_content: yes
      register: github_api

    - name: SIMPLENOTE - Register latest release
      set_fact:
        github_release: "{{ github_api.json.tag_name }}"

    - name: SIMPLENOTE - Creates temporary directory
      file:
        path: "{{ simplenote_tmp }}"
        state: directory

    - name: SIMPLENOTE - Download package
      get_url:
        url: "https://github.com/{{ github_project }}/releases/download/{{ github_release }}/Simplenote-linux-{{ github_release | regex_replace('^v') }}-amd64.deb"
        dest: "{{ simplenote_tmp }}/simplenote.deb"
        force: yes

    - name: SIMPLENOTE - Install package
      apt:
        deb: "{{ simplenote_tmp }}/simplenote.deb"

    - name: SIMPLENOTE - Remove temporary directory
      file:
        path: "{{ simplenote_tmp }}"
        state: absent
