- hosts: localhost
  connection: local
  become: yes

  vars:
    simplenote_version: 1.14.0
    simplenote_url: "https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/Simplenote-linux-{{ simplenote_version }}-amd64.deb"
    simplenote_tmp: "/tmp/simplenote"

  tasks:

    - name: SIMPLENOTE - Creates temporary directory
      file:
        path: "{{ simplenote_tmp }}"
        state: directory

    - name: SIMPLENOTE - Download package
      get_url:
        url: "{{ simplenote_url }}"
        dest: "{{ simplenote_tmp }}/simplenote.deb"
        force: yes

    - name: SIMPLENOTE - Install package
      apt:
        deb: "{{ simplenote_tmp }}/simplenote.deb"

    - name: SIMPLENOTE - Remove temporary directory
      file:
        path: "{{ simplenote_tmp }}"
        state: absent
