- hosts: localhost
  connection: local
  become: yes

  vars:
    slack_url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.10.0-amd64.deb
    slack_tmp: /tmp/slack

  tasks:

    - name: SLACK - Creates temporary directory
      file:
        path: "{{ slack_tmp }}"
        state: directory

    - name: SLACK - Download package
      get_url:
        url: "{{ slack_url }}"
        dest: "{{ slack_tmp }}/slack.deb"
        force: yes

    - name: SLACK - Install package
      apt:
        deb: "{{ slack_tmp }}/slack.deb"

    - name: SLACK - Remove temporary directory
      file:
        path: "{{ slack_tmp }}"
        state: absent