- hosts: localhost
  connection: local
  become: yes

  vars:
    # teams_url: "https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.7.0/teams-for-linux_0.7.0_amd64.deb"
    teams_url: "https://teams.microsoft.com/downloads/desktopurl?env=production&plat=linux&arch=x64&download=true&linuxArchiveType=deb"
    teams_tmp: "/tmp/teams"

  tasks:

    - name: TEAMS - Creates temporary directory
      file:
        path: "{{ teams_tmp }}"
        state: directory

    - name: TEAMS - Download package
      get_url:
        url: "{{ teams_url }}"
        dest: "{{ teams_tmp }}/teams.deb"
        force: yes

    - name: TEAMS - Install package
      apt:
        deb: "{{ teams_tmp }}/teams.deb"

    - name: TEAMS - Remove temporary directory
      file:
        path: "{{ teams_tmp }}"
        state: absent
