- hosts: localhost
  connection: local

  tasks:

    - name: TERMINATOR - install package
      become: yes
      apt:
        name: terminator
        state: present

    - name: TERMINATOR - Create config directory
      file:
        path: "~/.config/terminator"
        state: directory

    - name: TERMINATOR - default configuration
      become: no
      template:
        src: templates/terminator.j2
        dest: ~/.config/terminator/config
