- hosts: localhost
  connection: local

  tasks:

    - name: TWEAK - Enable universe repository
      become: yes
      shell: "add-apt-repository universe"

    - name: TWEAK - install packages
      become: yes
      apt:
        name:
          - gnome-tweak-tool
          - gnome-shell-extensions
          - gnome-shell-extension-workspaces-to-dock
        state: present
