- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: TYPORA - install pandoc
      package:
        name: pandoc
        state: present

    - name: TYPORA - add key
      become: yes
      apt_key:
        url: 'https://typora.io/linux/public-key.asc'
        state: present

    - name: TYPORA - install repository
      become: yes
      apt_repository:
        repo: deb https://typora.io/linux ./
        filename: typora
        state: present

    - name: TYPORA - install package
      become: yes
      apt:
        name: typora
        state: present