- hosts: localhost
  connection: local

  vars:
    virtualbox_tmp: /tmp/virtualbox

  tasks:

    - name: VIRTUALBOX - get the username
      become: false
      command: whoami
      register: whoami_output

    - name: VIRTUALBOX - add key
      become: yes
      apt_key:
        url: 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc'
        state: present

    - name: VIRTUALBOX - add repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
        filename: virtualbox
        state: present

    - name: VIRTUALBOX - install package
      become: yes
      apt:
        name: ["virtualbox-6.1"]
        state: present

    - name: VIRTUALBOX - add user to group vboxusers & disk
      become: yes
      command: "{{ item }}"
      with_items:
        - "usermod -a -G disk {{ whoami_output.stdout }}"
        - "usermod -a -G vboxusers {{ whoami_output.stdout }}"


    - name: VIRTUALBOX - Authorize virtual to use all USB
      become: yes
      shell: |
        echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf
        sysctl -p

    - name: VIRTUALBOX - Get Virtualbox version
      become: yes
      shell: |
        VBoxManage --version | cut -dr -f1 | cut -d'_' -f1 | tail -1
      register: version_output

    - name: VIRTUALBOX - Creates virtualbox extension temporary directory
      file:
        path: "{{ virtualbox_tmp }}"
        state: directory

    - name: VIRTUALBOX - Download virtualbox extension
      get_url:
        url: "http://download.virtualbox.org/virtualbox/{{ version_output.stdout }}/Oracle_VM_VirtualBox_Extension_Pack-{{ version_output.stdout }}.vbox-extpack"
        dest: "{{ virtualbox_tmp }}/Oracle_VM_VirtualBox_Extension_Pack-{{ version_output.stdout }}.vbox-extpack"
        force: yes

    - name: VIRTUALBOX - Install virtualbox extension
      become: yes
      shell: |
        VBoxManage extpack install --replace {{ virtualbox_tmp }}/Oracle_VM_VirtualBox_Extension_Pack-{{ version_output.stdout }}.vbox-extpack | echo "y"

    - name: VIRTUALBOX - Remove virtualbox extension temporary directory
      file:
        path: "{{ virtualbox_tmp }}"
        state: absent
