- hosts: localhost
  connection: local

  tasks:

    - name: install dependencies (apt)
      become: yes
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - gconf2
          - libasound2
          - libgtk2.0-0
          - libxss1
        state: present

    - name: install key (apt)
      become: yes
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present

    - name: install VS Code repo (apt)
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        state: present

    - name: install VS Code (apt)
      become: yes
      apt:
        name: "code"
        state: present

    - name: install VS Code extensions
      shell: code --install-extension {{ item }} --force
      with_items: 
        - ms-azuretools.vscode-docker
        - vscoss.vscode-ansible
        - mauve.terraform
        - rupisaini.vscode-ansible-linter
        - samuelcolvin.jinjahtml

# TODO configuration
# {
#     "workbench.startupEditor": "newUntitledFile",
#     "git.autofetch": true,
#     "python.linting.pylintEnabled": true,
#     "python.linting.enabled": true,
#     "python.pythonPath": "/usr/bin/python",
#     "workbench.tree.renderIndentGuides": "always",
#     "workbench.tree.indent": 16,
#     "terminal.integrated.shell.linux": "/bin/bash"
# }
#
# https://selivan.github.io/2018/09/27/vscode-ansible-files-open-right-syntax.html
# "files.associations": {
#     // Ansible
#     "**/defaults/**/*.yml": "jinja-yaml",
#     "**/group_vars/**/*": "jinja-yaml",
#     "**/host_vars/**/*": "jinja-yaml",
#     "**/vars/**/*.yml": "jinja-yaml",
#     "**/tasks/**/*.yml": "ansible",
#     "**/handlers/*.yml": "ansible",
#     "**/meta/*.yml": "ansible",
#     "**/roles/**/*.yml": "ansible",
#     "**/playbooks/**/*.yml": "ansible",
#     "**/ansible/**/hosts": "ini",
#     "**/ansible/**/inventory": "ini",
#     "ansible.cfg": "ini",
# },

# "[ansible]": {
#     "editor.detectIndentation": false,
#     "editor.tabSize": 2,
#     "editor.insertSpaces": true
# },
        
