- hosts: localhost
  connection: local
  become: false

  tasks:

    - name: GESTURES - get the username
      command: whoami
      register: whoami_output

    - name: VSCODE - install dependencies
      become: yes
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - gconf2
          - libasound2
          - libgtk2.0-0
          - libxss1
        state: present

    - name: VSCODE - add key
      become: yes
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present

    - name: VSCODE - add repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        state: present

    - name: VSCODE - install package
      become: yes
      apt:
        name: "code"
        state: present

    - name: VSCODE - install extensions
      shell: code --install-extension {{ item }} --force
      with_items:
        - donjayamanne.githistory
        - ms-azuretools.vscode-docker
        - vscoss.vscode-ansible
        - rupisaini.vscode-ansible-linter
        - HashiCorp.terraform
        - samuelcolvin.jinjahtml
        - ms-vscode.powershell
        - DavidAnson.vscode-markdownlint
        - Mikael.Angular-BeastCode
        - dracula-theme.theme-dracula
        - ms-vsliveshare.vsliveshare
        - bmarkovic.haproxy
        - golang.go
        - marp-team.marp-vscode

    - name: VSCODE - create configuration directory
      file:
        path: "/home/{{ whoami_output.stdout }}/.config/Code/User"
        state: directory

    - name: VSCODE - default user configuration
      become: no
      template:
        src: templates/settings.json.j2
        dest: "/home/{{ whoami_output.stdout }}/.config/Code/User/settings.json"
