- hosts: localhost
  connection: local

  tasks:

    - name: WINEHQ - add key
      become: yes
      apt_key:
        url: 'https://dl.winehq.org/wine-builds/winehq.key'
        state: present

    - name: WINEHQ - add repository Ubuntu 20.04
      become: yes
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ focal main
        state: present
      when: ansible_distribution_version == '20.04'

    - name: WINEHQ - add repository Ubuntu 19.10
      become: yes
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ eoan main
        state: present
      when: ansible_distribution_version == '19.10'

    - name: WINEHQ - add repository Ubuntu 18.04
      become: yes
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main
        state: present
      when: ansible_distribution_version == '18.04'

    - name: WINEHQ - add repository Ubuntu 16.04
      become: yes
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main
        state: present
      when: ansible_distribution_version == '16.04'

    - name: WINEHQ - install package
      become: yes
      apt:
        name:
          - winehq-stable
          - winetricks
        state: present
        update_cache: yes
