- hosts: localhost
  connection: local

  tasks:

    - name: WINEHQ - add key
      become: yes
      apt_key:
        url: 'https://dl.winehq.org/wine-builds/winehq.key'
        state: present

    - name: WINEHQ - add repository
      become: yes
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main
        filename: winehq
        state: present

    - name: WINEHQ - install package
      become: yes
      apt:
        name: winehq-stable
        state: present
