- hosts: localhost
  connection: local

  tasks:

    - name: GESTURES - get the username
      become: false
      command: whoami
      register: whoami_output

    - name: ZSH - install package
      become: yes
      apt:
        name:
          - curl
          - zsh
          - fonts-powerline
        state: present

    - name: ZSH - install oh-my-zsh
      become: no
      shell: 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
      ignore_errors: true

    - name: ZSH - install theme
      become: no
      git:
        repo: '{{ item }}'
        dest: "~/.oh-my-zsh/custom/themes/"
        force: yes
        clone: no
      with_items:
        - "https://github.com/bhilburn/powerlevel9k.git"

    - name: ZSH - install plugin
      become: no
      git:
        repo: '{{ item }}'
        dest: "~/.oh-my-zsh/custom/plugins"
        force: yes
        clone: no
      with_items:
        - "https://github.com/zsh-users/zsh-docker.git"
        - "https://github.com/zsh-users/zsh-autosuggestions"
        - "https://github.com/zsh-users/zsh-syntax-highlighting.git"

    - name: ZSH - modify theme
      become: no
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="powerlevel9k/powerlevel9k"'

    - name: ZSH - set zsh as default shell
      become: yes
      user:
        name: "{{ whoami_output.stdout }}"
        shell: /bin/zsh

      # TODO : update plugin list
      # plugins=(
      #   git
      #   vscode
      #   docker
      #   terraform
      #   zsh-syntax-highlighting
      #   zsh-autosuggestions
      # )
