- hosts: localhost
  connection: local

  tasks:

    - name: GESTURES - get the username
      become: false
      command: whoami
      register: whoami_output

    - name: ZSH - install package
      become: yes
      apt:
        name:
          - curl
          - zsh
          - fonts-powerline
          - autojump
        state: present

    - name: ZSH - check previous install
      become: no
      stat:
        path: ~/.oh-my-zsh
      register: file_details

    - name: ZSH - install oh-my-zsh
      become: no
      shell: 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
      when: file_details.stat.exists == false

    # - name: ZSH - install powerlevel9k theme
    #   become: no
    #   git:
    #     repo: 'https://github.com/bhilburn/powerlevel9k.git'
    #     dest: "~/.oh-my-zsh/custom/themes/powerlevel9k"

    - name: ZSH - install dracula theme
      become: no
      git:
        repo: 'https://github.com/dracula/zsh.git'
        dest: "~/.oh-my-zsh/custom/themes/dracula"


    - name: ZSH - install plugin
      become: no
      git:
        repo: 'https://github.com/zsh-users/{{ item }}.git'
        dest: "~/.oh-my-zsh/custom/plugins/{{ item }}"
      with_items:
        - "zsh-docker"
        - "zsh-autosuggestions"
        - "zsh-syntax-highlighting"

    - name: ZSH - modify options and theme
      become: no
      lineinfile:
        path: ~/.zshrc
        regexp: '^{{ item.key }}='
        line: '{{ item.key }}={{ item.value }}'
        state: present
      with_items:
        - { key: 'ZSH_THEME', value: '"dracula/dracula"' }
        #- { key: 'POWERLEVEL9K_LEFT_PROMPT_ELEMENTS', value: '(host ssh root_indicator dir dir_writable vcs command_execution_time status)' }
        #- { key: 'POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS', value: '()' }
        #- { key: 'POWERLEVEL9K_PROMPT_ON_NEWLINE', value: 'true' }
        #- { key: 'POWERLEVEL9K_PROMPT_ADD_NEWLINE', value: 'true' }
        #- { key: 'POWERLEVEL9K_SHORTEN_DIR_LENGTH', value: '2' }
        #- { key: 'POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX', value: '"%F{blue}\u256D\u2500%f"' }
        #- { key: 'POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX', value: '"%F{blue}\u2570\u27A4%f "' }
        - { key: 'ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE', value: '"fg=#444444,bold,underline"' }
        - { key: 'ZSH_AUTOSUGGEST_STRATEGY', value: '(history completion)' }
        - { key: 'plugins', value: '(git vscode docker docker-compose terraform helm kubectl kube-ps1 minikube httpie zsh-syntax-highlighting zsh-autosuggestions autojump direnv)' }

    - name: ZSH - add exception for make command completion
      become: no
      lineinfile:
        path: ~/.zshrc
        line: "zstyle ':completion:*:*:make:*' tag-order 'targets'"
        insertafter: "^autoload.*"
        state: present

    - name: ZSH - set zsh as default shell
      become: yes
      user:
        name: "{{ whoami_output.stdout }}"
        shell: /bin/zsh
